language: python
python:
    - "2.7"

#command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r test_requirements.txt
  - pip install -r package/requirements.txt --extra-index-url https://testpypi.python.org/simple
  - pip install "cloudshell-shell-core>=3.1.0,<3.2.0"
  - pip install "cloudshell-automation-api>=8.3.0.0,<8.3.1.0" --extra-index-url https://testpypi.python.org/simple
  - pip install "cloudshell-cp-core>=1.0.0,<1.1.0" --extra-index-url https://test.pypi.org/simple
  - pip install coveralls

script:
    - pushd package
    - python setup.py develop
    - popd
    - python runtests.py --with-coverage  --cover-package=package --exclude setup.py

after_success:
    - coveralls

notifications:
    - webhools: https://qualisystems-openstack-shell.getbadges.io/api/app/webhook/84540771-02fa-4b6c-8dea-7ed8719b3a52
